// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulcvmqhlwndvokydrsrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsY3ZtcWhsd25kdm9reWRyc3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTQzNzcsImV4cCI6MjA3MzMzMDM3N30.U_phInkIx81b0DmJwO1ZrQ9y7gMTI0EDM60bTJRNFso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});